Theoretical Questions:

In [ ]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Answer:-

# NumPy is a Python library that provides powerful tools for numerical computing. 

#  It enhances Python's capabilities by offering:
#1.Efficient Arrays: NumPy introduces the ndarray object, which allows for efficient storage and manipulation of large datasets, much faster than Python's built-in lists.
# 2.Mathematical Functions: It includes a wide range of mathematical functions to perform complex calculations on arrays, like matrix operations, Fourier transforms, and statistical analyses.
# 3.Vectorization: NumPy enables vectorized operations, meaning you can apply functions to entire arrays without writing loops, making the code faster and easier to read.
# 4.Interoperability: It integrates well with other scientific computing libraries like SciPy and Pandas, making it a key tool in data analysis workflows.

# NumPy makes numerical operations in Python more efficient, faster, and easier, which is essential for scientific computing and data analysis.

In [ ]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Answer:-

# np.mean() and np.average() in NumPy calculate the average of an array, but they have some differences:

# np.mean():-
# Purpose: Computes the simple arithmetic mean (average) of the elements in an array.
# Usage: Use when you want a straightforward average of values.
# example of np.mean():-
import numpy as np
data = np.array([1, 2, 3, 4, 5])
result = np.mean(data)
print(result)
Results- 3.0



# np.average():-
# Purpose: Computes the weighted average, where each element can have a different weight.
# Usage: Use when you need to account for different weights for elements
# example of np.average():-
weights = np.array([1, 2, 3, 4, 5])
result = np.average(data, weights=weights)  
print(result)
Results- 3.6666666666666665

In [ ]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for ID and 2D arrays.

Answer:-

# you can reverse an array along different axes using slicing or specific functions. 

# 1. Reversing a 1D Array:- Method: Use slicing with [::-1] to reverse the array.

# Example of 1D Array reverse:-
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)
print("===================")
Results-
[5 4 3 2 1]
===================



# 2. Reversing a 2D Array:- You can reverse along different axes:

# a.Reversing along rows (axis 0):-Method: Use slicing [::-1, :].
# Example of  Reversing along rows (axis 0):-

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)
print("================")
Results-
[[7 8 9]
 [4 5 6]
 [1 2 3]]
================


# b.Reversing along columns (axis 1):-Method: Use slicing [:, ::-1].
# Example of Reversing along columns (axis 1):-
reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)
print("===============")
Results-
[[3 2 1]
 [6 5 4]
 [9 8 7]]
===============


# C.Reversing both axes:-Method: Use slicing [::-1, ::-1].
# Example of Reversing both axes:-
reversed_both = arr_2d[::-1, ::-1]
print(reversed_both)
Results-
[[9 8 7]
 [6 5 4]
 [3 2 1]]

In [ ]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Answer:-

# the data type of elements in a NumPy array, you can use the .dtype attribute. Here's how you do it:

# 1.Memory Management:
# Efficient Storage: Different data types use different amounts of memory. For example, an int32 takes 4 bytes, while an int64 takes 8 bytes. Choosing the right data type can save memory, especially with large arrays.
# Example: Using int8 (1 byte) instead of int64 (8 bytes) for storing small integers reduces memory usage by 8 times.
        
# 2.Performance:
# Faster Operations: Operations on smaller data types (e.g., int32 vs. int64) are generally faster because they require less data to be processed.
# Example: If you’re performing calculations on a large dataset of small integers, using int32 instead of int64 can speed up the computations.
# Data Type Check: Use .dtype to determine the data type.
#Importance: Proper data type selection optimizes memory usage and improves computational speed, which is crucial in handling large datasets.

Ex- 
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)  
Results- int64

In [ ]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Answer:-

# It is a powerful, multidimensional container for homogeneous data, meaning all elements have the same data type.

# Key Features of ndarrays:
# 1.Multidimensionality: ndarrays can have multiple dimensions, such as 1D (vectors), 2D (matrices), or higher dimensions.
# 2.Homogeneous Data: All elements in an ndarray must be of the same data type (e.g., all integers, all floats).
# 3.Efficient Memory Use: ndarrays are stored in contiguous memory locations, which allows for fast access and efficient storage compared to standard Python lists.
# 4.Broadcasting: NumPy supports broadcasting, which allows operations on arrays of different shapes without needing explicit looping.
# 5.Vectorized Operations: Operations on ndarrays are applied element-wise without the need for explicit loops, leading to faster and more concise code.

    
# Differences from Standard Python Lists:
# 1.Data Type Consistency
# ndarray: All elements must have the same data type.
# Python List: Elements can have mixed data types.
       
    
# 2.Performance:

# ndarray: Faster for numerical computations due to contiguous memory storage and support for vectorized operations.
# Python List: Slower for large-scale numerical operations because it lacks these optimizations.
        
    
# 3.Memory Efficiency:
# ndarray: More memory-efficient due to fixed-size elements and contiguous memory layout.
# Python List: Less memory-efficient, with each element being a full-fledged Python object, leading to overhead.
        
    
# 4.Multidimensional Support:
# ndarray: Naturally supports multiple dimensions, such as 2D, 3D, etc.
# Python List: Can mimic multidimensionality with nested lists, but it is less efficient and harder to work with.

In [ ]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Answer:-

# NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to:

# 1.Faster Computations:
# NumPy arrays are optimized for numerical operations with C-based implementation, making them much faster than Python lists, especially for large datasets.


# 2.Memory Efficiency:
# NumPy arrays use contiguous memory and fixed-size elements, reducing memory usage compared to Python lists, which have overhead due to each element being a full Python object.


# 3.Vectorized Operations:
# NumPy supports vectorized operations, allowing you to perform element-wise calculations without explicit loops, which speeds up processing.
# NumPy arrays are faster, more memory-efficient, and support vectorized operations, making them ideal for large-scale numerical tasks compared to Python lists.

In [ ]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Answer:-

# vstack() and hstack() are used to stack arrays along different axes:

# 1. vstack() (Vertical Stack):- Purpose: Stacks arrays vertically (row-wise), one on top of the other.

Ex-
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.vstack((arr1, arr2))
print(result)
print("=================")
Results- 
[[1 2 3]
 [4 5 6]]
=================


# 2.hstack() (Horizontal Stack):-Purpose: Stacks arrays horizontally (column-wise), side by side.
Ex-
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.hstack((arr1, arr2))
print(result)
Results-
[1 2 3 4 5 6]

In [ ]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

Answer:-

#fliplr() and flipud() are used to reverse the order of elements in arrays along different dimensions:

#fliplr() (Flip Left-Right):-
#Purpose: Reverses the order of elements along the horizontal axis (left to right).
#Effect: Applies to 2D arrays, flipping columns from left to right.
Ex-
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.fliplr(arr)
print(result)
print("=========================================")
Results-
[[3 2 1]
 [6 5 4]]
=========================================


# flipud() (Flip Up-Down):-
#Purpose: Reverses the order of elements along the vertical axis (top to bottom).
#Effect: Applies to 2D arrays, flipping rows from top to bottom
        
Ex- 
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.flipud(arr)
print(result)
Results-
[[4 5 6]
 [1 2 3]]

In [ ]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Answer:-

# the array_split() method in NumPy is used to split an array into multiple sub-arrays. It provides flexibility in how the array is divided, including handling cases where the array cannot be evenly split.


# Functionality:
# Purpose: To split an array into a specified number of sub-arrays or based on specific indices.
# Usage: np.array_split(array, indices_or_sections)


# Handling Uneven Splits:
# Even Splits: If the total number of elements can be evenly divided by the number of sections, each sub-array will have the same size.
# Uneven Splits: When the total number of elements does not divide evenly, the resulting sub-arrays will have sizes as equal as possible. Some sub-arrays may have one more element than others.

# Splitting into Equal Sections:-
Ex- 
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = np.array_split(arr, 4)
print(result)
Results-[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

# Splitting by Indices::-
Ex- 
indices = [2, 5, 7]
result = np.array_split(arr, indices)
print(result)
Results-[array([1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]

In [ ]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Answer:-

# Vectorization:
# Concept: Vectorization refers to applying operations on entire arrays at once, rather than using explicit loops. This leverages low-level optimizations for faster computation.

# Example: Instead of looping through each element to add 5, you can do:
import numpy as np
arr = np.array([1, 2, 3])
result = arr + 5  

print(result)
print("=========================")
Results-
[6 7 8]
=========================


# Broadcasting:
# Concept: Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array to match the larger one’s shape.
Ex-
arr = np.array([[1, 2], [3, 4]])
result = arr + 10
print(result)
print("========================================================")
Results-
[[11 12]
 [13 14]]
========================================================


import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])
print(arr_2d)
print("============================")
print(arr_1d)
print("===========================")
result = arr_2d * arr_1d
print(result)
Results-
[[1 2 3]
 [4 5 6]]
============================
[10 20 30]
===========================
[[ 10  40  90]
 [ 40 100 180]]

Practical Questions:

In [ ]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

Answer:-


import numpy as np

arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)
print("================================")
print("\nTransposed Array:")

print(arr.T)
Results-
Original Array:
[[55 49 57]
 [31 11 44]
 [16 23 88]]
================================

Transposed Array:
[[55 31 16]
 [49 11 23]
 [57 44 88]]

In [ ]:
#2. Generate a ID NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

Answer:-

import numpy as np
arr_1d = np.arange(10)
print("Original 1D Array:")
print(arr_1d)
print("=======================")
Results-
Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]
=======================


# Reshape the 1D array into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(arr_2x5)
print("===================")
Results-
Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
===================


# Reshape the 2x5 array into a 5x2 array
arr_5x2 = arr_2x5.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(arr_5x2)
Results-
Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

Answer:-

import numpy as np

# Create a 4x4 array with random float values
arr_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(arr_4x4)
print("===========================")
Results-
Original 4x4 Array:
[[0.05800716 0.29064603 0.58216316 0.60941128]
 [0.37868156 0.65306847 0.54691625 0.38697215]
 [0.66436172 0.52065112 0.54066659 0.3682084 ]
 [0.77402872 0.7284984  0.55421911 0.52680138]]
===========================

# Add a border of zeros around the 4x4 array
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:")
print(arr_6x6)
Results-
6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.67678351 0.1233247  0.9605861  0.57407076 0.        ]
 [0.         0.79233077 0.51695286 0.42276771 0.96793444 0.        ]
 [0.         0.85742747 0.90244378 0.75020919 0.11590939 0.        ]
 [0.         0.54443164 0.7132332  0.59851512 0.30338116 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]

In [ ]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

Answer:-

import numpy as np
arr = np.arange(10, 65, 5)
print(arr)
Results-[10 15 20 25 30 35 40 45 50 55 60]

In [ ]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

Answer:-

import numpy as np

arr = np.array(['python', 'numpy', 'pandas'])

uppercase = np.char.upper(arr)
lowercase = np.char.lower(arr)
titlecase = np.char.title(arr)

print("Original Array:")
print(arr)
print("\nUppercase:")
print(uppercase)
print("\nLowercase:")
print(lowercase)
print("\nTitle Case:")
print(titlecase)
Results-
Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

Answer:-

# Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy'])

# Insert a space between each character of every word
words_with_spaces = np.char.join(' ', words)

# Print the result
print("Original Array:")
print(words)
print("\nWords with Spaces:")
print(words_with_spaces)
Results-
Original Array:
['hello' 'world' 'numpy']

Words with Spaces:
['h e l l o' 'w o r l d' 'n u m p y']

In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

Answer:-

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)
Results- 
Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]

In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

Answer:-

import numpy as np
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:")
print(identity_matrix)

print("Diagonal Elements:")
print(diagonal_elements)
Results-
Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
[1. 1. 1. 1. 1.]

In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

Answer:-

import numpy as np

# Simplified function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    # Check for factors from 5 to sqrt(n)
    for i in range(5, int(n**0.5) + 1, 6):
        if n % i == 0 or n % (i + 2) == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find and sort all prime numbers in the array
prime_numbers = np.array(sorted([num for num in random_array if is_prime(num)]))

print("Random Array:")
print(random_array)

print("Sorted Prime Numbers:")
print(prime_numbers)
Results-
Random Array:
[988 873 617 828  21 884 668 280 266 230 789 169 984 358 148 365 196 267
 850 416 440 861 425 194 149 193 313 392 270 994 444 968  21 321 953 713
 983 236 984  79 243 643 594 924 144 381 106 955 566 155 676 948 971 786
 878 316 310 544 776  39 342 440 954 742 747 577 318 219 981 416 680 426
 697 752 474 107 193 981 923 459 736 478  31 139 659 717 904 203 579 492
 221 309 379 373 186 292 810 317 708  92]
Sorted Prime Numbers:
[ 31  79 107 139 149 193 193 313 317 373 379 577 617 643 659 953 971 983]

In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

Answer:-

import numpy as np

# Generate a NumPy array of daily temperatures for a month (30 days)
daily_temperatures = np.random.uniform(low=-10, high=35, size=28)

# Reshape the array into a 2D array where each row represents a week (4 weeks of 7 days)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures:")
print(daily_temperatures)

print("\nWeekly Temperatures:")
print(weekly_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)
Results-
Daily Temperatures:
[31.96682709 11.04385537 29.98016341 33.70131479  4.79462219 27.25289844
 20.04244863 30.05156134  1.30996354 31.43258834  2.67128908 28.99997028
  7.46903437  8.9047947  17.33031348 19.99152432 23.91397999 17.36495716
  1.36121735 -8.27898379 -2.41973935  2.04734531 10.73714552 -1.34141712
  4.60504398 23.87424881  4.45297311 -9.99117696]

Weekly Temperatures:
[[31.96682709 11.04385537 29.98016341 33.70131479  4.79462219 27.25289844
  20.04244863]
 [30.05156134  1.30996354 31.43258834  2.67128908 28.99997028  7.46903437
   8.9047947 ]
 [17.33031348 19.99152432 23.91397999 17.36495716  1.36121735 -8.27898379
  -2.41973935]
 [ 2.04734531 10.73714552 -1.34141712  4.60504398 23.87424881  4.45297311
  -9.99117696]]

Weekly Averages:
[22.68316142 15.83417166  9.89475274  4.91202324]